//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAddRequest
    {
        public int idProductAddRequest { get; set; }
        public int idProduct { get; set; }
        public Nullable<int> idUser { get; set; }
        public int idProductAddRequestStatus { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ProductAddRequestStatus ProductAddRequestStatus { get; set; }
        public virtual User User { get; set; }
    }
}
