//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Storage
    {
        public int idProduct_Storage { get; set; }
        public int idProduct { get; set; }
        public int idStorage { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Storage Storage { get; set; }
    }
}
