//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketplace.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sell_User
    {
        public int idSell_User { get; set; }
        public int idUser { get; set; }
        public int idSell { get; set; }
    
        public virtual Sell Sell { get; set; }
        public virtual User User { get; set; }
    }
}
